atmMoney: 1000000

spring:
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
  file:
    name: C:/Users/hp/Desktop/demo/log.txt